Areas/Admin/Controllers/AdminOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CNWEB.Models;
using X.PagedList;
using CNWEB.Models.Authentication;
namespace CNWEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin")]
    [Route("Admin/AdminOrders")]
    [HasCredential(RoleCode = "order")]
    public class AdminOrdersController : Controller
    {
        private readonly WebContext _context;

        public AdminOrdersController(WebContext context)
        {
            _context = context;
        }
        [Route("")]
        [Route("Index")]
        [HttpGet("Index")]
        [HasCredential(RoleCode = "order")]
        // GET: Admin/AdminOrders
        public IActionResult Index(int? page, string CatID)
        {
            /*var webContext = _context.Orders.Include(o => o.TransactStatus).Include(o => o.User);
            return View(await webContext.ToListAsync());*/
          /*  var username = HttpContext.Session.GetString("Username");
            var fullname = HttpContext.Session.GetString("Name");
            var id = HttpContext.Session.GetString("ID");
            var image = HttpContext.Session.GetString("Image");
            var phone = HttpContext.Session.GetString("Phone");
            // Đặt thông tin người dùng vào ViewBag
            ViewBag.Username = username;
            ViewBag.fullname = fullname;*/
            var pageNumber = page ?? 1;
            var pageSize = 5;

            var lsProducts = from x in _context.Orders select x;

             ViewData["DanhMuc"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "Status", CatID);
            /*  var orders = _context.Orders.Where(x => x.TransactStatusId == CatID);
              return View(orders);*/
            if (!String.IsNullOrEmpty(CatID))
            {
                lsProducts = lsProducts.Where(x =>
         x.Id.ToLower().Contains(CatID) || (x.Address != null && x.Address.ToLower().Contains(CatID)) || 
           _context.Customers.Any(c => c.Id == x.UserId && c.Name.ToLower().Contains(CatID)) || _context.Customers.Any(c => c.Id == x.UserId && c.Email.ToLower().Contains(CatID)) ||
     (_context.TransactStatuses.Any(c => c.TransactStatusId == x.TransactStatusId && c.Status != null && c.Status.ToLower().Contains(CatID)))
     // Add other fields for search here
     );
            }

            var totalProducts = lsProducts.Count();
            ViewBag.totalPages = (int)Math.Ceiling(totalProducts / (double)pageSize);
            var pagedList = new X.PagedList.PagedList<Order>(lsProducts.OrderBy(x => x.Id), pageNumber, pageSize);
            /*  var Categories = _context.Categories.ToList();*/
            /*     Categories.Insert(0, new Category(_context) { Id = "00", Names = "-------Danh Mục------" });*/
            var startRange = (pageNumber - 1) * pageSize + 1;
            var endRange = Math.Min(pageNumber * pageSize, totalProducts);
            /*  ViewBag.CatID = new SelectList(Categories, "Id", "Names", CatID);*/
         /*   ViewBag.IdTradeMark = new SelectList(_context.TradeMarks.ToList(), "Id", "Names");
            ViewBag.IdCategories = new SelectList(_context.Categories.ToList(), "Id", "Names");*/
            ViewBag.TotalRecords = totalProducts;
            ViewBag.CatIDValue = CatID;
            /* ViewBag.CurrentCatID = CatID;*/
            ViewBag.CurrentPage = pageNumber;
            ViewBag.StartRange = startRange;
            ViewBag.EndRange = endRange;
            /*  ViewData["DanhMuc"] = new SelectList(_context.Categories, "Id", "Names");*/

            return View(pagedList); // Trả về danh sách đã phân trang cho view
        }
        [Route("")]
        [Route("Details")]
        [HttpGet("Details")]
        [HasCredential(RoleCode = "view-order")]
        // GET: Admin/AdminOrders/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.TransactStatus)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }
            var chitietdonhang = _context.OrderDetails.Include(x=>x.Product).AsNoTracking().Where(x=>x.OrderId==order.Id).OrderBy(x=>x.Id).ToList();
            ViewBag.chitiet = chitietdonhang;
            return View(order);
        }
        [HttpGet]
     /*   public IActionResult Filtter(string CatID = null)
        {
            var url = $"/Admin/AdminOrders?CatID={CatID}";
            if (string.IsNullOrEmpty(CatID))
            {
                url = $"/Admin/AdminOrders";
            }
            return Json(new { status = "success", redirectUrl = url });
        }*/
        [Route("")]
        [Route("Create")]
        [HttpGet("Create")]
       
        // GET: Admin/AdminOrders/Create
        public IActionResult Create()
        {
            ViewData["TransactStatusId"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "TransactStatusId");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Admin/AdminOrders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Route("Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Address,Amount,OrderDate,Phone,TransactStatusId,UserId,Status")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TransactStatusId"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "TransactStatusId", order.TransactStatusId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

            [Route("")]
        [Route("Edit")]
        [HttpGet("Edit")]
        // GET: Admin/AdminOrders/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["TransactStatusId"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "TransactStatusId", order.TransactStatusId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // POST: Admin/AdminOrders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /*     [Route("")]
             [Route("UpdateTT")]
             *//*    [Route("Edit")]*/
        [HttpGet]
        public IActionResult GetData()
        {
            // Lấy dữ liệu mới từ cơ sở dữ liệu hoặc bất kỳ nguồn nào khác
            var data = _context.Orders.ToList();

            // Trả về một phần view chứa dữ liệu mới
            return PartialView("_RecordsTablePartial", data); // Thay thế _RecordsTablePartial bằng tên của file view chứa bảng dữ liệu của bạn
        }
        [Route("")]
        [Route("UpdateTT")]
        /*    [Route("Edit")]*/
        [HttpPost]
        [HasCredential(RoleCode = "edit-order")]
        /*   [ValidateAntiForgeryToken]*/
        public IActionResult UpdateTT(string id, string trangthai)
        {

            var item = _context.Orders.Find(id);
            if (item != null)
            {
                _context.Orders.Attach(item);
                if (trangthai == "01")
                {
                    item.TransactStatusId = "01";
                }
                else if (trangthai == "02")
                {
                    item.TransactStatusId = "02";
                }
                else if (trangthai == "03")
                {
                    item.TransactStatusId = "03";
                }
                else if (trangthai == "04")
                {
                    item.TransactStatusId = "04";
                }

                _context.Entry(item).Property(x => x.TransactStatusId).IsModified = true;
                _context.SaveChanges();
                return Json(new { message = "Success", Success = true });
            }

            return Json(new { Message = "Unsuccess", Success = false });
        }
        /*        public IActionResult UpdateTT(string id, string trangthai)
                {

                    var item = _context.Orders.Find(id);
                    if (item != null)
                    {
                        _context.Orders.Attach(item);
                        if (trangthai == "01")
                        {
                            item.TransactStatusId = "01";
                        }
                        else if (trangthai == "02")
                        {
                            item.TransactStatusId = "02";
                        }
                        else if (trangthai == "03")
                        {
                            item.TransactStatusId = "03";
                        }
                        else if (trangthai == "04")
                        {
                            item.TransactStatusId = "04";
                        }

Areas/Admin/Views/AdminOrders/Create.cshtml
@model CNWEB.Models.Order

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransactStatusId" class="control-label"></label>
                <select asp-for="TransactStatusId" class ="form-control" asp-items="ViewBag.TransactStatusId"></select>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/AdminOrders/Delete.cshtml
@model CNWEB.Models.Order

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TransactStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TransactStatus.TransactStatusId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Areas/Admin/Views/AdminOrders/Details.cshtml
@model CNWEB.Models.Order

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    List<OrderDetail> orderDetails = ViewBag.chitiet;
}
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a><a asp-area="Admin" asp-controller="AdminOrders" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Danh sách đơn hàng</a>
            <span class="breadcrumb-item active">Chi tiết đơn hàng</span>
        </nav>
    </div>
</div>
<div class="card">
<div class="card-body">
    <div id="invoice" class="p-h-30">
        <div class="row m-t-20 lh-2">
            <div class="col-sm-9">
                <h3 class="p-l-10 m-t-10">Thông tin đơn hàng:</h3>
                <address class="p-l-10 m-t-10">
                    <span class="font-weight-semibold text-dark">Họ và tên: @Model.User.Name</span><br>
                    <span>Địa chỉ: @Model.Address</span><br>
                        <span>Số điện thoại: @Model.Phone</span><br>
                        <span>Email: @Model.User.Email</span>
                </address>
            </div>
            <div class="col-sm-3">
                <div class="m-t-80" style="margin-top: 50px">
                    <div class="text-dark text-uppercase d-inline-block">
                        <span class="font-weight-semibold text-dark">Mã đơn hàng :</span>
                    </div>
                    <div class="float-right">@Model.Id</div>
                </div>
                <div class="text-dark text-uppercase d-inline-block">
                    <span class="font-weight-semibold text-dark">Thời gian đặt hàng :</span>
                </div>
                <div class="float-right">@Model.OrderDate</div>
                    <div class="text-dark text-uppercase d-inline-block">
                        <span class="font-weight-semibold text-dark">Trạng thái đơn hàng :</span>
                    </div>
                    <div class="float-right">@Model.TransactStatus.Status</div>
            </div>
        </div>
            <div> <h3 class="p-l-10 m-t-10">Danh sách sản phẩm:</h3><br /></div>
        <div class="m-t-20">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Sản Phẩm</th>
                            <th>Số lượng</th>
                            <th>Giá</th>
                            <th>Thành Tiền</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(orderDetails != null && orderDetails.Count()>0)
                        {
                            foreach(var item in orderDetails)
                            {
                                int i = 1;
                                <tr>
                                    <th>@i</th>
                                    <td><a>@item.Product.Name</a></td>
                                    <td>@item.Quantity</td>
                                    <td>@item.Price VND</td>
                                    <td>@item.Total VND</td>
                                </tr>
                                i++;
                            }
                        }
                     
                     
                    </tbody>
                </table>
            </div>
            <div class="row m-t-30 lh-1-8">
                <div class="col-sm-12">
                    <div class="float-right text-right">
                   
                        <hr>
                        <h3><span class="font-weight-semibold text-dark">Tổng tiền :</span> @Model.Amount VNĐ</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

Areas/Admin/Views/AdminOrders/Edit.cshtml
@model CNWEB.Models.Order

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransactStatusId" class="control-label"></label>
                <select asp-for="TransactStatusId" class="form-control" asp-items="ViewBag.TransactStatusId"></select>
                <span asp-validation-for="TransactStatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>